### ISSUE TITLE
Unknown BNFTP packet?

### ISSUE THREAD

**Issue by cen1** [diegonc/packet-bnetp#9]
I forked this repo some time ago to fix a weird problem I encountered in one of my dumps but never had the time to do it. I see the repo is active again so I am reporting it here also.

[bnftp_unknown.zip](https://github.com/diegonc/packet-bnetp/files/1714982/bnftp_unknown.zip)

See the Unknown packet 0x72 and 0x8c.

**Comment by xpeh-owns** [comment]
It's bnftp procotol (tcp.stream eq 5) which is falsely decoded as bnetp.

**Comment by xpeh-owns** [comment]
https://www.google.com/search?q=45.90412704114N+13.88411692491E

**Comment by diegonc** [comment]
What @xpeh-owns says :)

The BNETP procotol performs FTP transfers to get some files from the server using the same port. If you look at frames 16 to 19, you can see the packets sent by the client to request this "subprotocol".

However, the dissector is attached to the TCP port and, since we don't support this kind of protocol switch, the plugin tries to dissect every frame as part of the same protocol, even if it just contains a piece of a random file.

**Comment by xpeh-owns** [comment]
Isn't there a state per TCP session?

**Comment by diegonc** [comment]
Wireshark has the concept of conversations to support this kind of use-cases. But I'm not sure if they are available from a Lua dissector.

**Comment by xpeh-owns** [comment]
@cen1, it's for you https://www.google.com/search?q=45.90412704114N+13.88411692491E
